### ISSUE TITLE
Error: github.GitHub is not a constructor

### ISSUE THREAD

**Issue by callumlocke** [dorshinar/get-deployment-url#11]
This action looks great and I really want to get it working, but when I run it, I just get this output (I've changed the repo details to `*****` as it's a private repo):

```
Run dorshinar/get-deployment-url@v1.0.7
  with:
    token: ***
    retryInterval: 10000
Starting to run with following input: {
  repo: '********',
  owner: '********',
  branch: '********'
}
Error: github.GitHub is not a constructor
```

Here is my complete `.github/workflows/audit.yml`:

```yaml
name: Audit

on:
  pull_request:
    types: [opened, reopened]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:

    - name: Get deployment URL
      id: deployment
      uses: dorshinar/get-deployment-url@v1.0.7
      timeout-minutes: 5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: TODO - some kind of audit
      run: npm run audit-site
      env:
        deployment: ${{ steps.deployment.outputs.deployment }}
```

Any ideas what the problem might be?
