### ISSUE TITLE
github.GitHub is not a constructor

### ISSUE THREAD

**Issue by ocervell** [dorshinar/get-deployment-url#16]
```
Run dorshinar/get-deployment-url@v1.0.7
Starting to run with following input: {
  repo: 'robot***',
  owner: 'openfoodfacts',
  branch: 'deploy-grafana-annotation'
}
Error: github.GitHub is not a constructor
```

for:
```
    - name: Get deployment URL
      if: ${{ always() }}
      id: get-deployment
      uses: dorshinar/get-deployment-url@v1.0.7
      timeout-minutes: 5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```
