### ISSUE TITLE
`retryInterval` default and input not working, rate limit exceeded

### ISSUE THREAD

**Issue by jefk** [dorshinar/get-deployment-url#5]
`retryInterval` default setting is not working. I've tried manually setting the retry interval as well, but requests are fired without any interval between.

Here's my step:

```
- name: Get deployment URL
  id: deployment_url
  uses: dorshinar/get-deployment-url@v1.0.0
  timeout-minutes: 5
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    retryInterval: 10000
```

In the logs, I can see that requests are not waiting for ten seconds. Also [console.log](https://github.com/dorshinar/get-deployment-url/blob/master/index.js#L11) appears that `retryInterval` is undefined. Eventually the rate limit is exceeded, log output:

```
environmentUrl is null, waiting  milliseconds and trying again
environmentUrl is null, waiting  milliseconds and trying again
##[error]API rate limit exceeded
```

**Comment by jefk** [comment]
I was able to get a default interval working in #6 , although I'm still not sure why setting `retryInterval` explicitly does not work

**Comment by dorshinar** [comment]
Have you tried it with the latest release?

Try running it with the following configuration:
```yml
- name: Get deployment URL
  id: deployment_url
  uses: dorshinar/get-deployment-url@v1.0.6
  timeout-minutes: 5
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    retryInterval: 10000
```
